//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../target/dependency/io/reactivex/internal/util/ExceptionHelper.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "io/reactivex/exceptions/CompositeException.h"
#include "io/reactivex/internal/util/ExceptionHelper.h"
#include "java/lang/Error.h"
#include "java/lang/IllegalStateException.h"
#include "java/lang/RuntimeException.h"
#include "java/util/ArrayDeque.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"
#include "java/util/concurrent/atomic/AtomicReference.h"

@interface IoReactivexInternalUtilExceptionHelper ()

- (instancetype)init;

@end

__attribute__((unused)) static void IoReactivexInternalUtilExceptionHelper_init(IoReactivexInternalUtilExceptionHelper *self);

__attribute__((unused)) static IoReactivexInternalUtilExceptionHelper *new_IoReactivexInternalUtilExceptionHelper_init() NS_RETURNS_RETAINED;

__attribute__((unused)) static IoReactivexInternalUtilExceptionHelper *create_IoReactivexInternalUtilExceptionHelper_init();

@interface IoReactivexInternalUtilExceptionHelper_1 : NSException

- (instancetype)initWithNSString:(NSString *)x0;

- (NSException *)fillInStackTrace;

@end

J2OBJC_EMPTY_STATIC_INIT(IoReactivexInternalUtilExceptionHelper_1)

inline jlong IoReactivexInternalUtilExceptionHelper_1_get_serialVersionUID();
#define IoReactivexInternalUtilExceptionHelper_1_serialVersionUID -4649703670690200604LL
J2OBJC_STATIC_FIELD_CONSTANT(IoReactivexInternalUtilExceptionHelper_1, serialVersionUID, jlong)

__attribute__((unused)) static void IoReactivexInternalUtilExceptionHelper_1_initWithNSString_(IoReactivexInternalUtilExceptionHelper_1 *self, NSString *x0);

__attribute__((unused)) static IoReactivexInternalUtilExceptionHelper_1 *new_IoReactivexInternalUtilExceptionHelper_1_initWithNSString_(NSString *x0) NS_RETURNS_RETAINED;

__attribute__((unused)) static IoReactivexInternalUtilExceptionHelper_1 *create_IoReactivexInternalUtilExceptionHelper_1_initWithNSString_(NSString *x0);

J2OBJC_INITIALIZED_DEFN(IoReactivexInternalUtilExceptionHelper)

NSException *IoReactivexInternalUtilExceptionHelper_TERMINATED;

@implementation IoReactivexInternalUtilExceptionHelper

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  IoReactivexInternalUtilExceptionHelper_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (JavaLangRuntimeException *)wrapOrThrowWithNSException:(NSException *)error {
  return IoReactivexInternalUtilExceptionHelper_wrapOrThrowWithNSException_(error);
}

+ (jboolean)addThrowableWithJavaUtilConcurrentAtomicAtomicReference:(JavaUtilConcurrentAtomicAtomicReference *)field
                                                    withNSException:(NSException *)exception {
  return IoReactivexInternalUtilExceptionHelper_addThrowableWithJavaUtilConcurrentAtomicAtomicReference_withNSException_(field, exception);
}

+ (NSException *)terminateWithJavaUtilConcurrentAtomicAtomicReference:(JavaUtilConcurrentAtomicAtomicReference *)field {
  return IoReactivexInternalUtilExceptionHelper_terminateWithJavaUtilConcurrentAtomicAtomicReference_(field);
}

+ (id<JavaUtilList>)flattenWithNSException:(NSException *)t {
  return IoReactivexInternalUtilExceptionHelper_flattenWithNSException_(t);
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x2, -1, -1, -1, -1, -1, -1 },
    { NULL, "LJavaLangRuntimeException;", 0x9, 0, 1, -1, -1, -1, -1 },
    { NULL, "Z", 0x9, 2, 3, -1, 4, -1, -1 },
    { NULL, "LNSException;", 0x9, 5, 6, -1, 7, -1, -1 },
    { NULL, "LJavaUtilList;", 0x9, 8, 1, -1, 9, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(init);
  methods[1].selector = @selector(wrapOrThrowWithNSException:);
  methods[2].selector = @selector(addThrowableWithJavaUtilConcurrentAtomicAtomicReference:withNSException:);
  methods[3].selector = @selector(terminateWithJavaUtilConcurrentAtomicAtomicReference:);
  methods[4].selector = @selector(flattenWithNSException:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "TERMINATED", "LNSException;", .constantValue.asLong = 0, 0x19, -1, 10, -1, -1 },
  };
  static const void *ptrTable[] = { "wrapOrThrow", "LNSException;", "addThrowable", "LJavaUtilConcurrentAtomicAtomicReference;LNSException;", "<T:Ljava/lang/Object;>(Ljava/util/concurrent/atomic/AtomicReference<Ljava/lang/Throwable;>;Ljava/lang/Throwable;)Z", "terminate", "LJavaUtilConcurrentAtomicAtomicReference;", "<T:Ljava/lang/Object;>(Ljava/util/concurrent/atomic/AtomicReference<Ljava/lang/Throwable;>;)Ljava/lang/Throwable;", "flatten", "(Ljava/lang/Throwable;)Ljava/util/List<Ljava/lang/Throwable;>;", &IoReactivexInternalUtilExceptionHelper_TERMINATED };
  static const J2ObjcClassInfo _IoReactivexInternalUtilExceptionHelper = { "ExceptionHelper", "io.reactivex.internal.util", ptrTable, methods, fields, 7, 0x11, 5, 1, -1, -1, -1, -1, -1 };
  return &_IoReactivexInternalUtilExceptionHelper;
}

+ (void)initialize {
  if (self == [IoReactivexInternalUtilExceptionHelper class]) {
    JreStrongAssignAndConsume(&IoReactivexInternalUtilExceptionHelper_TERMINATED, new_IoReactivexInternalUtilExceptionHelper_1_initWithNSString_(@"No further exceptions"));
    J2OBJC_SET_INITIALIZED(IoReactivexInternalUtilExceptionHelper)
  }
}

@end

void IoReactivexInternalUtilExceptionHelper_init(IoReactivexInternalUtilExceptionHelper *self) {
  NSObject_init(self);
  @throw create_JavaLangIllegalStateException_initWithNSString_(@"No instances!");
}

IoReactivexInternalUtilExceptionHelper *new_IoReactivexInternalUtilExceptionHelper_init() {
  J2OBJC_NEW_IMPL(IoReactivexInternalUtilExceptionHelper, init)
}

IoReactivexInternalUtilExceptionHelper *create_IoReactivexInternalUtilExceptionHelper_init() {
  J2OBJC_CREATE_IMPL(IoReactivexInternalUtilExceptionHelper, init)
}

JavaLangRuntimeException *IoReactivexInternalUtilExceptionHelper_wrapOrThrowWithNSException_(NSException *error) {
  IoReactivexInternalUtilExceptionHelper_initialize();
  if ([error isKindOfClass:[JavaLangError class]]) {
    @throw (JavaLangError *) cast_chk(error, [JavaLangError class]);
  }
  if ([error isKindOfClass:[JavaLangRuntimeException class]]) {
    return (JavaLangRuntimeException *) cast_chk(error, [JavaLangRuntimeException class]);
  }
  return create_JavaLangRuntimeException_initWithNSException_(error);
}

jboolean IoReactivexInternalUtilExceptionHelper_addThrowableWithJavaUtilConcurrentAtomicAtomicReference_withNSException_(JavaUtilConcurrentAtomicAtomicReference *field, NSException *exception) {
  IoReactivexInternalUtilExceptionHelper_initialize();
  for (; ; ) {
    NSException *current = [((JavaUtilConcurrentAtomicAtomicReference *) nil_chk(field)) get];
    if (current == IoReactivexInternalUtilExceptionHelper_TERMINATED) {
      return false;
    }
    NSException *update;
    if (current == nil) {
      update = exception;
    }
    else {
      update = create_IoReactivexExceptionsCompositeException_initWithNSExceptionArray_([IOSObjectArray arrayWithObjects:(id[]){ current, exception } count:2 type:NSException_class_()]);
    }
    if ([field compareAndSetWithId:current withId:update]) {
      return true;
    }
  }
}

NSException *IoReactivexInternalUtilExceptionHelper_terminateWithJavaUtilConcurrentAtomicAtomicReference_(JavaUtilConcurrentAtomicAtomicReference *field) {
  IoReactivexInternalUtilExceptionHelper_initialize();
  NSException *current = [((JavaUtilConcurrentAtomicAtomicReference *) nil_chk(field)) get];
  if (current != IoReactivexInternalUtilExceptionHelper_TERMINATED) {
    current = [field getAndSetWithId:IoReactivexInternalUtilExceptionHelper_TERMINATED];
  }
  return current;
}

id<JavaUtilList> IoReactivexInternalUtilExceptionHelper_flattenWithNSException_(NSException *t) {
  IoReactivexInternalUtilExceptionHelper_initialize();
  id<JavaUtilList> list = create_JavaUtilArrayList_init();
  JavaUtilArrayDeque *deque = create_JavaUtilArrayDeque_init();
  [deque offerWithId:t];
  while (![deque isEmpty]) {
    NSException *e = [deque removeFirst];
    if ([e isKindOfClass:[IoReactivexExceptionsCompositeException class]]) {
      IoReactivexExceptionsCompositeException *ce = (IoReactivexExceptionsCompositeException *) cast_chk(e, [IoReactivexExceptionsCompositeException class]);
      id<JavaUtilList> exceptions = [((IoReactivexExceptionsCompositeException *) nil_chk(ce)) getExceptions];
      for (jint i = [((id<JavaUtilList>) nil_chk(exceptions)) size] - 1; i >= 0; i--) {
        [deque offerFirstWithId:[exceptions getWithInt:i]];
      }
    }
    else {
      [list addWithId:e];
    }
  }
  return list;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(IoReactivexInternalUtilExceptionHelper)

@implementation IoReactivexInternalUtilExceptionHelper_1

- (instancetype)initWithNSString:(NSString *)x0 {
  IoReactivexInternalUtilExceptionHelper_1_initWithNSString_(self, x0);
  return self;
}

- (NSException *)fillInStackTrace {
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSException;", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithNSString:);
  methods[1].selector = @selector(fillInStackTrace);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = IoReactivexInternalUtilExceptionHelper_1_serialVersionUID, 0x1a, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LNSString;", "LIoReactivexInternalUtilExceptionHelper;" };
  static const J2ObjcClassInfo _IoReactivexInternalUtilExceptionHelper_1 = { "", "io.reactivex.internal.util", ptrTable, methods, fields, 7, 0x8018, 2, 1, 1, -1, -1, -1, -1 };
  return &_IoReactivexInternalUtilExceptionHelper_1;
}

@end

void IoReactivexInternalUtilExceptionHelper_1_initWithNSString_(IoReactivexInternalUtilExceptionHelper_1 *self, NSString *x0) {
  NSException_initWithNSString_(self, x0);
}

IoReactivexInternalUtilExceptionHelper_1 *new_IoReactivexInternalUtilExceptionHelper_1_initWithNSString_(NSString *x0) {
  J2OBJC_NEW_IMPL(IoReactivexInternalUtilExceptionHelper_1, initWithNSString_, x0)
}

IoReactivexInternalUtilExceptionHelper_1 *create_IoReactivexInternalUtilExceptionHelper_1_initWithNSString_(NSString *x0) {
  J2OBJC_CREATE_IMPL(IoReactivexInternalUtilExceptionHelper_1, initWithNSString_, x0)
}
