//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../target/dependency/okio/HashingSource.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OkioHashingSource")
#ifdef RESTRICT_OkioHashingSource
#define INCLUDE_ALL_OkioHashingSource 0
#else
#define INCLUDE_ALL_OkioHashingSource 1
#endif
#undef RESTRICT_OkioHashingSource

#if !defined (OkioHashingSource_) && (INCLUDE_ALL_OkioHashingSource || defined(INCLUDE_OkioHashingSource))
#define OkioHashingSource_

#define RESTRICT_OkioForwardingSource 1
#define INCLUDE_OkioForwardingSource 1
#include "okio/ForwardingSource.h"

@class OkioBuffer;
@class OkioByteString;
@protocol OkioSource;

@interface OkioHashingSource : OkioForwardingSource

#pragma mark Public

- (OkioByteString *)hash__;

+ (OkioHashingSource *)hmacSha1WithOkioSource:(id<OkioSource>)source
                           withOkioByteString:(OkioByteString *)key;

+ (OkioHashingSource *)hmacSha256WithOkioSource:(id<OkioSource>)source
                             withOkioByteString:(OkioByteString *)key;

+ (OkioHashingSource *)md5WithOkioSource:(id<OkioSource>)source;

- (jlong)readWithOkioBuffer:(OkioBuffer *)sink
                   withLong:(jlong)byteCount;

+ (OkioHashingSource *)sha1WithOkioSource:(id<OkioSource>)source;

+ (OkioHashingSource *)sha256WithOkioSource:(id<OkioSource>)source;

@end

J2OBJC_EMPTY_STATIC_INIT(OkioHashingSource)

FOUNDATION_EXPORT OkioHashingSource *OkioHashingSource_md5WithOkioSource_(id<OkioSource> source);

FOUNDATION_EXPORT OkioHashingSource *OkioHashingSource_sha1WithOkioSource_(id<OkioSource> source);

FOUNDATION_EXPORT OkioHashingSource *OkioHashingSource_sha256WithOkioSource_(id<OkioSource> source);

FOUNDATION_EXPORT OkioHashingSource *OkioHashingSource_hmacSha1WithOkioSource_withOkioByteString_(id<OkioSource> source, OkioByteString *key);

FOUNDATION_EXPORT OkioHashingSource *OkioHashingSource_hmacSha256WithOkioSource_withOkioByteString_(id<OkioSource> source, OkioByteString *key);

J2OBJC_TYPE_LITERAL_HEADER(OkioHashingSource)

#endif

#pragma pop_macro("INCLUDE_ALL_OkioHashingSource")
