//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../target/dependency/io/reactivex/internal/util/ErrorMode.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_IoReactivexInternalUtilErrorMode")
#ifdef RESTRICT_IoReactivexInternalUtilErrorMode
#define INCLUDE_ALL_IoReactivexInternalUtilErrorMode 0
#else
#define INCLUDE_ALL_IoReactivexInternalUtilErrorMode 1
#endif
#undef RESTRICT_IoReactivexInternalUtilErrorMode

#if !defined (IoReactivexInternalUtilErrorMode_) && (INCLUDE_ALL_IoReactivexInternalUtilErrorMode || defined(INCLUDE_IoReactivexInternalUtilErrorMode))
#define IoReactivexInternalUtilErrorMode_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, IoReactivexInternalUtilErrorMode_Enum) {
  IoReactivexInternalUtilErrorMode_Enum_IMMEDIATE = 0,
  IoReactivexInternalUtilErrorMode_Enum_BOUNDARY = 1,
  IoReactivexInternalUtilErrorMode_Enum_END = 2,
};

@interface IoReactivexInternalUtilErrorMode : JavaLangEnum < NSCopying >

#pragma mark Public

+ (IoReactivexInternalUtilErrorMode *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (id)copyWithZone:(NSZone *)zone;

@end

J2OBJC_STATIC_INIT(IoReactivexInternalUtilErrorMode)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT IoReactivexInternalUtilErrorMode *IoReactivexInternalUtilErrorMode_values_[];

inline IoReactivexInternalUtilErrorMode *IoReactivexInternalUtilErrorMode_get_IMMEDIATE();
J2OBJC_ENUM_CONSTANT(IoReactivexInternalUtilErrorMode, IMMEDIATE)

inline IoReactivexInternalUtilErrorMode *IoReactivexInternalUtilErrorMode_get_BOUNDARY();
J2OBJC_ENUM_CONSTANT(IoReactivexInternalUtilErrorMode, BOUNDARY)

inline IoReactivexInternalUtilErrorMode *IoReactivexInternalUtilErrorMode_get_END();
J2OBJC_ENUM_CONSTANT(IoReactivexInternalUtilErrorMode, END)

FOUNDATION_EXPORT IOSObjectArray *IoReactivexInternalUtilErrorMode_values();

FOUNDATION_EXPORT IoReactivexInternalUtilErrorMode *IoReactivexInternalUtilErrorMode_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT IoReactivexInternalUtilErrorMode *IoReactivexInternalUtilErrorMode_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(IoReactivexInternalUtilErrorMode)

#endif

#pragma pop_macro("INCLUDE_ALL_IoReactivexInternalUtilErrorMode")
