//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../target/dependency/io/reactivex/CompletableEmitter.java
//

#include "J2ObjC_source.h"
#include "io/reactivex/CompletableEmitter.h"

@interface IoReactivexCompletableEmitter : NSObject

@end

@implementation IoReactivexCompletableEmitter

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "V", 0x401, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 2, 3, -1, -1, -1, -1 },
    { NULL, "V", 0x401, 4, 5, -1, -1, -1, -1 },
    { NULL, "Z", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(onComplete);
  methods[1].selector = @selector(onErrorWithNSException:);
  methods[2].selector = @selector(setDisposableWithIoReactivexDisposablesDisposable:);
  methods[3].selector = @selector(setCancellableWithIoReactivexFunctionsCancellable:);
  methods[4].selector = @selector(isDisposed);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "onError", "LNSException;", "setDisposable", "LIoReactivexDisposablesDisposable;", "setCancellable", "LIoReactivexFunctionsCancellable;" };
  static const J2ObjcClassInfo _IoReactivexCompletableEmitter = { "CompletableEmitter", "io.reactivex", ptrTable, methods, NULL, 7, 0x609, 5, 0, -1, -1, -1, -1, -1 };
  return &_IoReactivexCompletableEmitter;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(IoReactivexCompletableEmitter)
