//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../target/dependency/org/junit/internal/runners/rules/ValidationError.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Exception.h"
#include "org/junit/internal/runners/rules/ValidationError.h"
#include "org/junit/runners/model/FrameworkMember.h"

@implementation OrgJunitInternalRunnersRulesValidationError

- (instancetype)initWithOrgJunitRunnersModelFrameworkMember:(OrgJunitRunnersModelFrameworkMember *)member
                                               withIOSClass:(IOSClass *)annotation
                                               withNSString:(NSString *)suffix {
  OrgJunitInternalRunnersRulesValidationError_initWithOrgJunitRunnersModelFrameworkMember_withIOSClass_withNSString_(self, member, annotation, suffix);
  return self;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithOrgJunitRunnersModelFrameworkMember:withIOSClass:withNSString:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "LOrgJunitRunnersModelFrameworkMember;LIOSClass;LNSString;", "(Lorg/junit/runners/model/FrameworkMember<*>;Ljava/lang/Class<+Ljava/lang/annotation/Annotation;>;Ljava/lang/String;)V" };
  static const J2ObjcClassInfo _OrgJunitInternalRunnersRulesValidationError = { "ValidationError", "org.junit.internal.runners.rules", ptrTable, methods, NULL, 7, 0x0, 1, 0, -1, -1, -1, -1, -1 };
  return &_OrgJunitInternalRunnersRulesValidationError;
}

@end

void OrgJunitInternalRunnersRulesValidationError_initWithOrgJunitRunnersModelFrameworkMember_withIOSClass_withNSString_(OrgJunitInternalRunnersRulesValidationError *self, OrgJunitRunnersModelFrameworkMember *member, IOSClass *annotation, NSString *suffix) {
  JavaLangException_initWithNSString_(self, NSString_java_formatWithNSString_withNSObjectArray_(@"The @%s '%s' %s", [IOSObjectArray arrayWithObjects:(id[]){ [((IOSClass *) nil_chk(annotation)) getSimpleName], [((OrgJunitRunnersModelFrameworkMember *) nil_chk(member)) getName], suffix } count:3 type:NSObject_class_()]));
}

OrgJunitInternalRunnersRulesValidationError *new_OrgJunitInternalRunnersRulesValidationError_initWithOrgJunitRunnersModelFrameworkMember_withIOSClass_withNSString_(OrgJunitRunnersModelFrameworkMember *member, IOSClass *annotation, NSString *suffix) {
  J2OBJC_NEW_IMPL(OrgJunitInternalRunnersRulesValidationError, initWithOrgJunitRunnersModelFrameworkMember_withIOSClass_withNSString_, member, annotation, suffix)
}

OrgJunitInternalRunnersRulesValidationError *create_OrgJunitInternalRunnersRulesValidationError_initWithOrgJunitRunnersModelFrameworkMember_withIOSClass_withNSString_(OrgJunitRunnersModelFrameworkMember *member, IOSClass *annotation, NSString *suffix) {
  J2OBJC_CREATE_IMPL(OrgJunitInternalRunnersRulesValidationError, initWithOrgJunitRunnersModelFrameworkMember_withIOSClass_withNSString_, member, annotation, suffix)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgJunitInternalRunnersRulesValidationError)
