//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../target/dependency/io/reactivex/internal/operators/single/SingleDoOnSuccess.java
//

#include "J2ObjC_source.h"
#include "io/reactivex/Single.h"
#include "io/reactivex/SingleObserver.h"
#include "io/reactivex/SingleSource.h"
#include "io/reactivex/disposables/Disposable.h"
#include "io/reactivex/exceptions/Exceptions.h"
#include "io/reactivex/functions/Consumer.h"
#include "io/reactivex/internal/operators/single/SingleDoOnSuccess.h"

@interface IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1 : NSObject < IoReactivexSingleObserver > {
 @public
  IoReactivexInternalOperatorsSingleSingleDoOnSuccess *this$0_;
  id<IoReactivexSingleObserver> val$s_;
}

- (instancetype)initWithIoReactivexInternalOperatorsSingleSingleDoOnSuccess:(IoReactivexInternalOperatorsSingleSingleDoOnSuccess *)outer$
                                              withIoReactivexSingleObserver:(id<IoReactivexSingleObserver>)capture$0;

- (void)onSubscribeWithIoReactivexDisposablesDisposable:(id<IoReactivexDisposablesDisposable>)d;

- (void)onSuccessWithId:(id)value;

- (void)onErrorWithNSException:(NSException *)e;

@end

J2OBJC_EMPTY_STATIC_INIT(IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1)

__attribute__((unused)) static void IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1_initWithIoReactivexInternalOperatorsSingleSingleDoOnSuccess_withIoReactivexSingleObserver_(IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1 *self, IoReactivexInternalOperatorsSingleSingleDoOnSuccess *outer$, id<IoReactivexSingleObserver> capture$0);

__attribute__((unused)) static IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1 *new_IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1_initWithIoReactivexInternalOperatorsSingleSingleDoOnSuccess_withIoReactivexSingleObserver_(IoReactivexInternalOperatorsSingleSingleDoOnSuccess *outer$, id<IoReactivexSingleObserver> capture$0) NS_RETURNS_RETAINED;

__attribute__((unused)) static IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1 *create_IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1_initWithIoReactivexInternalOperatorsSingleSingleDoOnSuccess_withIoReactivexSingleObserver_(IoReactivexInternalOperatorsSingleSingleDoOnSuccess *outer$, id<IoReactivexSingleObserver> capture$0);

@implementation IoReactivexInternalOperatorsSingleSingleDoOnSuccess

- (instancetype)initWithIoReactivexSingleSource:(id<IoReactivexSingleSource>)source
               withIoReactivexFunctionsConsumer:(id<IoReactivexFunctionsConsumer>)onSuccess {
  IoReactivexInternalOperatorsSingleSingleDoOnSuccess_initWithIoReactivexSingleSource_withIoReactivexFunctionsConsumer_(self, source, onSuccess);
  return self;
}

- (void)subscribeActualWithIoReactivexSingleObserver:(id<IoReactivexSingleObserver>)s {
  [((id<IoReactivexSingleSource>) nil_chk(source_)) subscribeWithIoReactivexSingleObserver:create_IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1_initWithIoReactivexInternalOperatorsSingleSingleDoOnSuccess_withIoReactivexSingleObserver_(self, s)];
}

- (void)dealloc {
  RELEASE_(source_);
  RELEASE_(onSuccess_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
    { NULL, "V", 0x4, 2, 3, -1, 4, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithIoReactivexSingleSource:withIoReactivexFunctionsConsumer:);
  methods[1].selector = @selector(subscribeActualWithIoReactivexSingleObserver:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "source_", "LIoReactivexSingleSource;", .constantValue.asLong = 0, 0x10, -1, -1, 5, -1 },
    { "onSuccess_", "LIoReactivexFunctionsConsumer;", .constantValue.asLong = 0, 0x10, -1, -1, 6, -1 },
  };
  static const void *ptrTable[] = { "LIoReactivexSingleSource;LIoReactivexFunctionsConsumer;", "(Lio/reactivex/SingleSource<TT;>;Lio/reactivex/functions/Consumer<-TT;>;)V", "subscribeActual", "LIoReactivexSingleObserver;", "(Lio/reactivex/SingleObserver<-TT;>;)V", "Lio/reactivex/SingleSource<TT;>;", "Lio/reactivex/functions/Consumer<-TT;>;", "<T:Ljava/lang/Object;>Lio/reactivex/Single<TT;>;" };
  static const J2ObjcClassInfo _IoReactivexInternalOperatorsSingleSingleDoOnSuccess = { "SingleDoOnSuccess", "io.reactivex.internal.operators.single", ptrTable, methods, fields, 7, 0x11, 2, 2, -1, -1, -1, 7, -1 };
  return &_IoReactivexInternalOperatorsSingleSingleDoOnSuccess;
}

@end

void IoReactivexInternalOperatorsSingleSingleDoOnSuccess_initWithIoReactivexSingleSource_withIoReactivexFunctionsConsumer_(IoReactivexInternalOperatorsSingleSingleDoOnSuccess *self, id<IoReactivexSingleSource> source, id<IoReactivexFunctionsConsumer> onSuccess) {
  IoReactivexSingle_init(self);
  JreStrongAssign(&self->source_, source);
  JreStrongAssign(&self->onSuccess_, onSuccess);
}

IoReactivexInternalOperatorsSingleSingleDoOnSuccess *new_IoReactivexInternalOperatorsSingleSingleDoOnSuccess_initWithIoReactivexSingleSource_withIoReactivexFunctionsConsumer_(id<IoReactivexSingleSource> source, id<IoReactivexFunctionsConsumer> onSuccess) {
  J2OBJC_NEW_IMPL(IoReactivexInternalOperatorsSingleSingleDoOnSuccess, initWithIoReactivexSingleSource_withIoReactivexFunctionsConsumer_, source, onSuccess)
}

IoReactivexInternalOperatorsSingleSingleDoOnSuccess *create_IoReactivexInternalOperatorsSingleSingleDoOnSuccess_initWithIoReactivexSingleSource_withIoReactivexFunctionsConsumer_(id<IoReactivexSingleSource> source, id<IoReactivexFunctionsConsumer> onSuccess) {
  J2OBJC_CREATE_IMPL(IoReactivexInternalOperatorsSingleSingleDoOnSuccess, initWithIoReactivexSingleSource_withIoReactivexFunctionsConsumer_, source, onSuccess)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(IoReactivexInternalOperatorsSingleSingleDoOnSuccess)

@implementation IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1

- (instancetype)initWithIoReactivexInternalOperatorsSingleSingleDoOnSuccess:(IoReactivexInternalOperatorsSingleSingleDoOnSuccess *)outer$
                                              withIoReactivexSingleObserver:(id<IoReactivexSingleObserver>)capture$0 {
  IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1_initWithIoReactivexInternalOperatorsSingleSingleDoOnSuccess_withIoReactivexSingleObserver_(self, outer$, capture$0);
  return self;
}

- (void)onSubscribeWithIoReactivexDisposablesDisposable:(id<IoReactivexDisposablesDisposable>)d {
  [((id<IoReactivexSingleObserver>) nil_chk(val$s_)) onSubscribeWithIoReactivexDisposablesDisposable:d];
}

- (void)onSuccessWithId:(id)value {
  @try {
    [((id<IoReactivexFunctionsConsumer>) nil_chk(this$0_->onSuccess_)) acceptWithId:value];
  }
  @catch (NSException *ex) {
    IoReactivexExceptionsExceptions_throwIfFatalWithNSException_(ex);
    [((id<IoReactivexSingleObserver>) nil_chk(val$s_)) onErrorWithNSException:ex];
    return;
  }
  [((id<IoReactivexSingleObserver>) nil_chk(val$s_)) onSuccessWithId:value];
}

- (void)onErrorWithNSException:(NSException *)e {
  [((id<IoReactivexSingleObserver>) nil_chk(val$s_)) onErrorWithNSException:e];
}

- (void)dealloc {
  RELEASE_(this$0_);
  RELEASE_(val$s_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x0, -1, -1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 0, 1, -1, -1, -1, -1 },
    { NULL, "V", 0x1, 2, 3, -1, 4, -1, -1 },
    { NULL, "V", 0x1, 5, 6, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithIoReactivexInternalOperatorsSingleSingleDoOnSuccess:withIoReactivexSingleObserver:);
  methods[1].selector = @selector(onSubscribeWithIoReactivexDisposablesDisposable:);
  methods[2].selector = @selector(onSuccessWithId:);
  methods[3].selector = @selector(onErrorWithNSException:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "this$0_", "LIoReactivexInternalOperatorsSingleSingleDoOnSuccess;", .constantValue.asLong = 0, 0x1012, -1, -1, 7, -1 },
    { "val$s_", "LIoReactivexSingleObserver;", .constantValue.asLong = 0, 0x1012, -1, -1, 8, -1 },
  };
  static const void *ptrTable[] = { "onSubscribe", "LIoReactivexDisposablesDisposable;", "onSuccess", "LNSObject;", "(TT;)V", "onError", "LNSException;", "Lio/reactivex/internal/operators/single/SingleDoOnSuccess<TT;>;", "Lio/reactivex/SingleObserver<-TT;>;", "LIoReactivexInternalOperatorsSingleSingleDoOnSuccess;", "subscribeActualWithIoReactivexSingleObserver:", "Ljava/lang/Object;Lio/reactivex/SingleObserver<TT;>;" };
  static const J2ObjcClassInfo _IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1 = { "", "io.reactivex.internal.operators.single", ptrTable, methods, fields, 7, 0x8018, 4, 2, 9, -1, 10, 11, -1 };
  return &_IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1;
}

@end

void IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1_initWithIoReactivexInternalOperatorsSingleSingleDoOnSuccess_withIoReactivexSingleObserver_(IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1 *self, IoReactivexInternalOperatorsSingleSingleDoOnSuccess *outer$, id<IoReactivexSingleObserver> capture$0) {
  JreStrongAssign(&self->this$0_, outer$);
  JreStrongAssign(&self->val$s_, capture$0);
  NSObject_init(self);
}

IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1 *new_IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1_initWithIoReactivexInternalOperatorsSingleSingleDoOnSuccess_withIoReactivexSingleObserver_(IoReactivexInternalOperatorsSingleSingleDoOnSuccess *outer$, id<IoReactivexSingleObserver> capture$0) {
  J2OBJC_NEW_IMPL(IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1, initWithIoReactivexInternalOperatorsSingleSingleDoOnSuccess_withIoReactivexSingleObserver_, outer$, capture$0)
}

IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1 *create_IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1_initWithIoReactivexInternalOperatorsSingleSingleDoOnSuccess_withIoReactivexSingleObserver_(IoReactivexInternalOperatorsSingleSingleDoOnSuccess *outer$, id<IoReactivexSingleObserver> capture$0) {
  J2OBJC_CREATE_IMPL(IoReactivexInternalOperatorsSingleSingleDoOnSuccess_1, initWithIoReactivexInternalOperatorsSingleSingleDoOnSuccess_withIoReactivexSingleObserver_, outer$, capture$0)
}
