//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../target/dependency/com/google/j2objc/annotations/Weak.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleJ2objcAnnotationsWeak")
#ifdef RESTRICT_ComGoogleJ2objcAnnotationsWeak
#define INCLUDE_ALL_ComGoogleJ2objcAnnotationsWeak 0
#else
#define INCLUDE_ALL_ComGoogleJ2objcAnnotationsWeak 1
#endif
#undef RESTRICT_ComGoogleJ2objcAnnotationsWeak

#if !defined (ComGoogleJ2objcAnnotationsWeak_) && (INCLUDE_ALL_ComGoogleJ2objcAnnotationsWeak || defined(INCLUDE_ComGoogleJ2objcAnnotationsWeak))
#define ComGoogleJ2objcAnnotationsWeak_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol ComGoogleJ2objcAnnotationsWeak < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleJ2objcAnnotationsWeak)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleJ2objcAnnotationsWeak)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleJ2objcAnnotationsWeak")
