//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../target/dependency/io/reactivex/internal/operators/flowable/FlowableZipIterable.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_IoReactivexInternalOperatorsFlowableFlowableZipIterable")
#ifdef RESTRICT_IoReactivexInternalOperatorsFlowableFlowableZipIterable
#define INCLUDE_ALL_IoReactivexInternalOperatorsFlowableFlowableZipIterable 0
#else
#define INCLUDE_ALL_IoReactivexInternalOperatorsFlowableFlowableZipIterable 1
#endif
#undef RESTRICT_IoReactivexInternalOperatorsFlowableFlowableZipIterable

#if !defined (IoReactivexInternalOperatorsFlowableFlowableZipIterable_) && (INCLUDE_ALL_IoReactivexInternalOperatorsFlowableFlowableZipIterable || defined(INCLUDE_IoReactivexInternalOperatorsFlowableFlowableZipIterable))
#define IoReactivexInternalOperatorsFlowableFlowableZipIterable_

#define RESTRICT_IoReactivexFlowable 1
#define INCLUDE_IoReactivexFlowable 1
#include "io/reactivex/Flowable.h"

@protocol IoReactivexFunctionsBiFunction;
@protocol JavaLangIterable;
@protocol OrgReactivestreamsPublisher;
@protocol OrgReactivestreamsSubscriber;

@interface IoReactivexInternalOperatorsFlowableFlowableZipIterable : IoReactivexFlowable {
 @public
  id<OrgReactivestreamsPublisher> source_;
  id<JavaLangIterable> other_;
  id<IoReactivexFunctionsBiFunction> zipper_;
}

#pragma mark Public

- (instancetype)initWithOrgReactivestreamsPublisher:(id<OrgReactivestreamsPublisher>)source
                               withJavaLangIterable:(id<JavaLangIterable>)other
                 withIoReactivexFunctionsBiFunction:(id<IoReactivexFunctionsBiFunction>)zipper;

- (void)subscribeActualWithOrgReactivestreamsSubscriber:(id<OrgReactivestreamsSubscriber>)t;

@end

J2OBJC_EMPTY_STATIC_INIT(IoReactivexInternalOperatorsFlowableFlowableZipIterable)

J2OBJC_FIELD_SETTER(IoReactivexInternalOperatorsFlowableFlowableZipIterable, source_, id<OrgReactivestreamsPublisher>)
J2OBJC_FIELD_SETTER(IoReactivexInternalOperatorsFlowableFlowableZipIterable, other_, id<JavaLangIterable>)
J2OBJC_FIELD_SETTER(IoReactivexInternalOperatorsFlowableFlowableZipIterable, zipper_, id<IoReactivexFunctionsBiFunction>)

FOUNDATION_EXPORT void IoReactivexInternalOperatorsFlowableFlowableZipIterable_initWithOrgReactivestreamsPublisher_withJavaLangIterable_withIoReactivexFunctionsBiFunction_(IoReactivexInternalOperatorsFlowableFlowableZipIterable *self, id<OrgReactivestreamsPublisher> source, id<JavaLangIterable> other, id<IoReactivexFunctionsBiFunction> zipper);

FOUNDATION_EXPORT IoReactivexInternalOperatorsFlowableFlowableZipIterable *new_IoReactivexInternalOperatorsFlowableFlowableZipIterable_initWithOrgReactivestreamsPublisher_withJavaLangIterable_withIoReactivexFunctionsBiFunction_(id<OrgReactivestreamsPublisher> source, id<JavaLangIterable> other, id<IoReactivexFunctionsBiFunction> zipper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT IoReactivexInternalOperatorsFlowableFlowableZipIterable *create_IoReactivexInternalOperatorsFlowableFlowableZipIterable_initWithOrgReactivestreamsPublisher_withJavaLangIterable_withIoReactivexFunctionsBiFunction_(id<OrgReactivestreamsPublisher> source, id<JavaLangIterable> other, id<IoReactivexFunctionsBiFunction> zipper);

J2OBJC_TYPE_LITERAL_HEADER(IoReactivexInternalOperatorsFlowableFlowableZipIterable)

#endif

#if !defined (IoReactivexInternalOperatorsFlowableFlowableZipIterable_ZipIterableSubscriber_) && (INCLUDE_ALL_IoReactivexInternalOperatorsFlowableFlowableZipIterable || defined(INCLUDE_IoReactivexInternalOperatorsFlowableFlowableZipIterable_ZipIterableSubscriber))
#define IoReactivexInternalOperatorsFlowableFlowableZipIterable_ZipIterableSubscriber_

#define RESTRICT_OrgReactivestreamsSubscriber 1
#define INCLUDE_OrgReactivestreamsSubscriber 1
#include "org/reactivestreams/Subscriber.h"

#define RESTRICT_OrgReactivestreamsSubscription 1
#define INCLUDE_OrgReactivestreamsSubscription 1
#include "org/reactivestreams/Subscription.h"

@protocol IoReactivexFunctionsBiFunction;
@protocol JavaUtilIterator;

@interface IoReactivexInternalOperatorsFlowableFlowableZipIterable_ZipIterableSubscriber : NSObject < OrgReactivestreamsSubscriber, OrgReactivestreamsSubscription > {
 @public
  id<OrgReactivestreamsSubscriber> actual_;
  id<JavaUtilIterator> iterator_;
  id<IoReactivexFunctionsBiFunction> zipper_;
  id<OrgReactivestreamsSubscription> s_;
  jboolean done_;
}

#pragma mark Public

- (void)cancel;

- (void)onComplete;

- (void)onErrorWithNSException:(NSException *)t;

- (void)onNextWithId:(id)t;

- (void)onSubscribeWithOrgReactivestreamsSubscription:(id<OrgReactivestreamsSubscription>)s;

- (void)requestWithLong:(jlong)n;

#pragma mark Package-Private

- (instancetype)initWithOrgReactivestreamsSubscriber:(id<OrgReactivestreamsSubscriber>)actual
                                withJavaUtilIterator:(id<JavaUtilIterator>)iterator
                  withIoReactivexFunctionsBiFunction:(id<IoReactivexFunctionsBiFunction>)zipper;

- (void)errorWithNSException:(NSException *)e;

@end

J2OBJC_EMPTY_STATIC_INIT(IoReactivexInternalOperatorsFlowableFlowableZipIterable_ZipIterableSubscriber)

J2OBJC_FIELD_SETTER(IoReactivexInternalOperatorsFlowableFlowableZipIterable_ZipIterableSubscriber, actual_, id<OrgReactivestreamsSubscriber>)
J2OBJC_FIELD_SETTER(IoReactivexInternalOperatorsFlowableFlowableZipIterable_ZipIterableSubscriber, iterator_, id<JavaUtilIterator>)
J2OBJC_FIELD_SETTER(IoReactivexInternalOperatorsFlowableFlowableZipIterable_ZipIterableSubscriber, zipper_, id<IoReactivexFunctionsBiFunction>)
J2OBJC_FIELD_SETTER(IoReactivexInternalOperatorsFlowableFlowableZipIterable_ZipIterableSubscriber, s_, id<OrgReactivestreamsSubscription>)

FOUNDATION_EXPORT void IoReactivexInternalOperatorsFlowableFlowableZipIterable_ZipIterableSubscriber_initWithOrgReactivestreamsSubscriber_withJavaUtilIterator_withIoReactivexFunctionsBiFunction_(IoReactivexInternalOperatorsFlowableFlowableZipIterable_ZipIterableSubscriber *self, id<OrgReactivestreamsSubscriber> actual, id<JavaUtilIterator> iterator, id<IoReactivexFunctionsBiFunction> zipper);

FOUNDATION_EXPORT IoReactivexInternalOperatorsFlowableFlowableZipIterable_ZipIterableSubscriber *new_IoReactivexInternalOperatorsFlowableFlowableZipIterable_ZipIterableSubscriber_initWithOrgReactivestreamsSubscriber_withJavaUtilIterator_withIoReactivexFunctionsBiFunction_(id<OrgReactivestreamsSubscriber> actual, id<JavaUtilIterator> iterator, id<IoReactivexFunctionsBiFunction> zipper) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT IoReactivexInternalOperatorsFlowableFlowableZipIterable_ZipIterableSubscriber *create_IoReactivexInternalOperatorsFlowableFlowableZipIterable_ZipIterableSubscriber_initWithOrgReactivestreamsSubscriber_withJavaUtilIterator_withIoReactivexFunctionsBiFunction_(id<OrgReactivestreamsSubscriber> actual, id<JavaUtilIterator> iterator, id<IoReactivexFunctionsBiFunction> zipper);

J2OBJC_TYPE_LITERAL_HEADER(IoReactivexInternalOperatorsFlowableFlowableZipIterable_ZipIterableSubscriber)

#endif

#pragma pop_macro("INCLUDE_ALL_IoReactivexInternalOperatorsFlowableFlowableZipIterable")
