//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../target/dependency/org/junit/AfterClass.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/annotation/Annotation.h"
#include "java/lang/annotation/ElementType.h"
#include "java/lang/annotation/Retention.h"
#include "java/lang/annotation/RetentionPolicy.h"
#include "java/lang/annotation/Target.h"
#include "org/junit/AfterClass.h"

__attribute__((unused)) static IOSObjectArray *OrgJunitAfterClass__Annotations$0();

@implementation OrgJunitAfterClass

- (IOSClass *)annotationType {
  return OrgJunitAfterClass_class_();
}

- (NSString *)description {
  return @"@org.junit.AfterClass()";
}

+ (const J2ObjcClassInfo *)__metadata {
  static const void *ptrTable[] = { (void *)&OrgJunitAfterClass__Annotations$0 };
  static const J2ObjcClassInfo _OrgJunitAfterClass = { "AfterClass", "org.junit", ptrTable, NULL, NULL, 7, 0x2609, 0, 0, -1, -1, -1, -1, 0 };
  return &_OrgJunitAfterClass;
}

@end

id<OrgJunitAfterClass> create_OrgJunitAfterClass() {
  OrgJunitAfterClass *self = AUTORELEASE([[OrgJunitAfterClass alloc] init]);
  return self;
}

IOSObjectArray *OrgJunitAfterClass__Annotations$0() {
  return [IOSObjectArray arrayWithObjects:(id[]){ create_JavaLangAnnotationRetention(JreLoadEnum(JavaLangAnnotationRetentionPolicy, RUNTIME)), create_JavaLangAnnotationTarget([IOSObjectArray arrayWithObjects:(id[]){ JreLoadEnum(JavaLangAnnotationElementType, METHOD) } count:1 type:JavaLangAnnotationElementType_class_()]) } count:2 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(OrgJunitAfterClass)
