//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../target/dependency/okhttp3/internal/http2/ConnectionShutdownException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Okhttp3InternalHttp2ConnectionShutdownException")
#ifdef RESTRICT_Okhttp3InternalHttp2ConnectionShutdownException
#define INCLUDE_ALL_Okhttp3InternalHttp2ConnectionShutdownException 0
#else
#define INCLUDE_ALL_Okhttp3InternalHttp2ConnectionShutdownException 1
#endif
#undef RESTRICT_Okhttp3InternalHttp2ConnectionShutdownException

#if !defined (Okhttp3InternalHttp2ConnectionShutdownException_) && (INCLUDE_ALL_Okhttp3InternalHttp2ConnectionShutdownException || defined(INCLUDE_Okhttp3InternalHttp2ConnectionShutdownException))
#define Okhttp3InternalHttp2ConnectionShutdownException_

#define RESTRICT_JavaIoIOException 1
#define INCLUDE_JavaIoIOException 1
#include "java/io/IOException.h"

@interface Okhttp3InternalHttp2ConnectionShutdownException : JavaIoIOException

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(Okhttp3InternalHttp2ConnectionShutdownException)

FOUNDATION_EXPORT void Okhttp3InternalHttp2ConnectionShutdownException_init(Okhttp3InternalHttp2ConnectionShutdownException *self);

FOUNDATION_EXPORT Okhttp3InternalHttp2ConnectionShutdownException *new_Okhttp3InternalHttp2ConnectionShutdownException_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT Okhttp3InternalHttp2ConnectionShutdownException *create_Okhttp3InternalHttp2ConnectionShutdownException_init();

J2OBJC_TYPE_LITERAL_HEADER(Okhttp3InternalHttp2ConnectionShutdownException)

#endif

#pragma pop_macro("INCLUDE_ALL_Okhttp3InternalHttp2ConnectionShutdownException")
