//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../target/dependency/retrofit2/Callback.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Retrofit2Callback")
#ifdef RESTRICT_Retrofit2Callback
#define INCLUDE_ALL_Retrofit2Callback 0
#else
#define INCLUDE_ALL_Retrofit2Callback 1
#endif
#undef RESTRICT_Retrofit2Callback

#if !defined (Retrofit2Callback_) && (INCLUDE_ALL_Retrofit2Callback || defined(INCLUDE_Retrofit2Callback))
#define Retrofit2Callback_

@class Retrofit2Response;
@protocol Retrofit2Call;

@protocol Retrofit2Callback < JavaObject >

- (void)onResponseWithRetrofit2Call:(id<Retrofit2Call>)call
              withRetrofit2Response:(Retrofit2Response *)response;

- (void)onFailureWithRetrofit2Call:(id<Retrofit2Call>)call
                   withNSException:(NSException *)t;

@end

J2OBJC_EMPTY_STATIC_INIT(Retrofit2Callback)

J2OBJC_TYPE_LITERAL_HEADER(Retrofit2Callback)

#endif

#pragma pop_macro("INCLUDE_ALL_Retrofit2Callback")
