//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../target/dependency/org/junit/runners/model/InitializationError.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/Exception.h"
#include "java/util/Arrays.h"
#include "java/util/List.h"
#include "org/junit/runners/model/InitializationError.h"

@interface OrgJunitRunnersModelInitializationError () {
 @public
  id<JavaUtilList> fErrors_;
}

@end

J2OBJC_FIELD_SETTER(OrgJunitRunnersModelInitializationError, fErrors_, id<JavaUtilList>)

inline jlong OrgJunitRunnersModelInitializationError_get_serialVersionUID();
#define OrgJunitRunnersModelInitializationError_serialVersionUID 1LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgJunitRunnersModelInitializationError, serialVersionUID, jlong)

@implementation OrgJunitRunnersModelInitializationError

- (instancetype)initWithJavaUtilList:(id<JavaUtilList>)errors {
  OrgJunitRunnersModelInitializationError_initWithJavaUtilList_(self, errors);
  return self;
}

- (instancetype)initWithNSException:(NSException *)error {
  OrgJunitRunnersModelInitializationError_initWithNSException_(self, error);
  return self;
}

- (instancetype)initWithNSString:(NSString *)string {
  OrgJunitRunnersModelInitializationError_initWithNSString_(self, string);
  return self;
}

- (id<JavaUtilList>)getCauses {
  return fErrors_;
}

- (void)dealloc {
  RELEASE_(fErrors_);
  [super dealloc];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, 1, -1, -1 },
    { NULL, NULL, 0x1, -1, 2, -1, -1, -1, -1 },
    { NULL, NULL, 0x1, -1, 3, -1, -1, -1, -1 },
    { NULL, "LJavaUtilList;", 0x1, -1, -1, -1, 4, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithJavaUtilList:);
  methods[1].selector = @selector(initWithNSException:);
  methods[2].selector = @selector(initWithNSString:);
  methods[3].selector = @selector(getCauses);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "serialVersionUID", "J", .constantValue.asLong = OrgJunitRunnersModelInitializationError_serialVersionUID, 0x1a, -1, -1, -1, -1 },
    { "fErrors_", "LJavaUtilList;", .constantValue.asLong = 0, 0x12, -1, -1, 5, -1 },
  };
  static const void *ptrTable[] = { "LJavaUtilList;", "(Ljava/util/List<Ljava/lang/Throwable;>;)V", "LNSException;", "LNSString;", "()Ljava/util/List<Ljava/lang/Throwable;>;", "Ljava/util/List<Ljava/lang/Throwable;>;" };
  static const J2ObjcClassInfo _OrgJunitRunnersModelInitializationError = { "InitializationError", "org.junit.runners.model", ptrTable, methods, fields, 7, 0x1, 4, 2, -1, -1, -1, -1, -1 };
  return &_OrgJunitRunnersModelInitializationError;
}

@end

void OrgJunitRunnersModelInitializationError_initWithJavaUtilList_(OrgJunitRunnersModelInitializationError *self, id<JavaUtilList> errors) {
  JavaLangException_init(self);
  JreStrongAssign(&self->fErrors_, errors);
}

OrgJunitRunnersModelInitializationError *new_OrgJunitRunnersModelInitializationError_initWithJavaUtilList_(id<JavaUtilList> errors) {
  J2OBJC_NEW_IMPL(OrgJunitRunnersModelInitializationError, initWithJavaUtilList_, errors)
}

OrgJunitRunnersModelInitializationError *create_OrgJunitRunnersModelInitializationError_initWithJavaUtilList_(id<JavaUtilList> errors) {
  J2OBJC_CREATE_IMPL(OrgJunitRunnersModelInitializationError, initWithJavaUtilList_, errors)
}

void OrgJunitRunnersModelInitializationError_initWithNSException_(OrgJunitRunnersModelInitializationError *self, NSException *error) {
  OrgJunitRunnersModelInitializationError_initWithJavaUtilList_(self, JavaUtilArrays_asListWithNSObjectArray_([IOSObjectArray arrayWithObjects:(id[]){ error } count:1 type:NSException_class_()]));
}

OrgJunitRunnersModelInitializationError *new_OrgJunitRunnersModelInitializationError_initWithNSException_(NSException *error) {
  J2OBJC_NEW_IMPL(OrgJunitRunnersModelInitializationError, initWithNSException_, error)
}

OrgJunitRunnersModelInitializationError *create_OrgJunitRunnersModelInitializationError_initWithNSException_(NSException *error) {
  J2OBJC_CREATE_IMPL(OrgJunitRunnersModelInitializationError, initWithNSException_, error)
}

void OrgJunitRunnersModelInitializationError_initWithNSString_(OrgJunitRunnersModelInitializationError *self, NSString *string) {
  OrgJunitRunnersModelInitializationError_initWithNSException_(self, create_JavaLangException_initWithNSString_(string));
}

OrgJunitRunnersModelInitializationError *new_OrgJunitRunnersModelInitializationError_initWithNSString_(NSString *string) {
  J2OBJC_NEW_IMPL(OrgJunitRunnersModelInitializationError, initWithNSString_, string)
}

OrgJunitRunnersModelInitializationError *create_OrgJunitRunnersModelInitializationError_initWithNSString_(NSString *string) {
  J2OBJC_CREATE_IMPL(OrgJunitRunnersModelInitializationError, initWithNSString_, string)
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(OrgJunitRunnersModelInitializationError)
