//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../target/dependency/io/reactivex/CompletableSource.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_IoReactivexCompletableSource")
#ifdef RESTRICT_IoReactivexCompletableSource
#define INCLUDE_ALL_IoReactivexCompletableSource 0
#else
#define INCLUDE_ALL_IoReactivexCompletableSource 1
#endif
#undef RESTRICT_IoReactivexCompletableSource

#if !defined (IoReactivexCompletableSource_) && (INCLUDE_ALL_IoReactivexCompletableSource || defined(INCLUDE_IoReactivexCompletableSource))
#define IoReactivexCompletableSource_

@protocol IoReactivexCompletableObserver;

@protocol IoReactivexCompletableSource < JavaObject >

- (void)subscribeWithIoReactivexCompletableObserver:(id<IoReactivexCompletableObserver>)cs;

@end

J2OBJC_EMPTY_STATIC_INIT(IoReactivexCompletableSource)

J2OBJC_TYPE_LITERAL_HEADER(IoReactivexCompletableSource)

#endif

#pragma pop_macro("INCLUDE_ALL_IoReactivexCompletableSource")
