//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: ../target/dependency/okhttp3/internal/cache/DiskLruCache.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_Okhttp3InternalCacheDiskLruCache")
#ifdef RESTRICT_Okhttp3InternalCacheDiskLruCache
#define INCLUDE_ALL_Okhttp3InternalCacheDiskLruCache 0
#else
#define INCLUDE_ALL_Okhttp3InternalCacheDiskLruCache 1
#endif
#undef RESTRICT_Okhttp3InternalCacheDiskLruCache

#if !defined (Okhttp3InternalCacheDiskLruCache_) && (INCLUDE_ALL_Okhttp3InternalCacheDiskLruCache || defined(INCLUDE_Okhttp3InternalCacheDiskLruCache))
#define Okhttp3InternalCacheDiskLruCache_

#define RESTRICT_JavaIoCloseable 1
#define INCLUDE_JavaIoCloseable 1
#include "java/io/Closeable.h"

#define RESTRICT_JavaIoFlushable 1
#define INCLUDE_JavaIoFlushable 1
#include "java/io/Flushable.h"

@class JavaIoFile;
@class JavaUtilLinkedHashMap;
@class JavaUtilRegexPattern;
@class Okhttp3InternalCacheDiskLruCache_Editor;
@class Okhttp3InternalCacheDiskLruCache_Entry;
@class Okhttp3InternalCacheDiskLruCache_Snapshot;
@protocol JavaUtilConcurrentExecutor;
@protocol JavaUtilIterator;
@protocol Okhttp3InternalIoFileSystem;
@protocol OkioBufferedSink;

@interface Okhttp3InternalCacheDiskLruCache : NSObject < JavaIoCloseable, JavaIoFlushable > {
 @public
  id<Okhttp3InternalIoFileSystem> fileSystem_;
  JavaIoFile *directory_;
  jint valueCount_;
  id<OkioBufferedSink> journalWriter_;
  JavaUtilLinkedHashMap *lruEntries_;
  jint redundantOpCount_;
  jboolean hasJournalErrors_;
  jboolean initialized_;
  jboolean closed_;
  jboolean mostRecentTrimFailed_;
  jboolean mostRecentRebuildFailed_;
}

#pragma mark Public

- (void)close;

+ (Okhttp3InternalCacheDiskLruCache *)createWithOkhttp3InternalIoFileSystem:(id<Okhttp3InternalIoFileSystem>)fileSystem
                                                             withJavaIoFile:(JavaIoFile *)directory
                                                                    withInt:(jint)appVersion
                                                                    withInt:(jint)valueCount
                                                                   withLong:(jlong)maxSize;

- (void)delete__;

- (Okhttp3InternalCacheDiskLruCache_Editor *)editWithNSString:(NSString *)key;

- (void)evictAll;

- (void)flush;

- (Okhttp3InternalCacheDiskLruCache_Snapshot *)getWithNSString:(NSString *)key;

- (JavaIoFile *)getDirectory;

- (jlong)getMaxSize;

- (void)initialize__ OBJC_METHOD_FAMILY_NONE;

- (jboolean)isClosed;

- (jboolean)removeWithNSString:(NSString *)key;

- (void)setMaxSizeWithLong:(jlong)maxSize;

- (jlong)size;

- (id<JavaUtilIterator>)snapshots;

#pragma mark Package-Private

- (instancetype)initWithOkhttp3InternalIoFileSystem:(id<Okhttp3InternalIoFileSystem>)fileSystem
                                     withJavaIoFile:(JavaIoFile *)directory
                                            withInt:(jint)appVersion
                                            withInt:(jint)valueCount
                                           withLong:(jlong)maxSize
                     withJavaUtilConcurrentExecutor:(id<JavaUtilConcurrentExecutor>)executor;

- (void)completeEditWithOkhttp3InternalCacheDiskLruCache_Editor:(Okhttp3InternalCacheDiskLruCache_Editor *)editor
                                                    withBoolean:(jboolean)success;

- (Okhttp3InternalCacheDiskLruCache_Editor *)editWithNSString:(NSString *)key
                                                     withLong:(jlong)expectedSequenceNumber;

- (jboolean)journalRebuildRequired;

- (void)rebuildJournal;

- (jboolean)removeEntryWithOkhttp3InternalCacheDiskLruCache_Entry:(Okhttp3InternalCacheDiskLruCache_Entry *)entry_;

- (void)trimToSize;

@end

J2OBJC_STATIC_INIT(Okhttp3InternalCacheDiskLruCache)

J2OBJC_FIELD_SETTER(Okhttp3InternalCacheDiskLruCache, fileSystem_, id<Okhttp3InternalIoFileSystem>)
J2OBJC_FIELD_SETTER(Okhttp3InternalCacheDiskLruCache, directory_, JavaIoFile *)
J2OBJC_FIELD_SETTER(Okhttp3InternalCacheDiskLruCache, journalWriter_, id<OkioBufferedSink>)
J2OBJC_FIELD_SETTER(Okhttp3InternalCacheDiskLruCache, lruEntries_, JavaUtilLinkedHashMap *)

inline NSString *Okhttp3InternalCacheDiskLruCache_get_JOURNAL_FILE();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *Okhttp3InternalCacheDiskLruCache_JOURNAL_FILE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(Okhttp3InternalCacheDiskLruCache, JOURNAL_FILE, NSString *)

inline NSString *Okhttp3InternalCacheDiskLruCache_get_JOURNAL_FILE_TEMP();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *Okhttp3InternalCacheDiskLruCache_JOURNAL_FILE_TEMP;
J2OBJC_STATIC_FIELD_OBJ_FINAL(Okhttp3InternalCacheDiskLruCache, JOURNAL_FILE_TEMP, NSString *)

inline NSString *Okhttp3InternalCacheDiskLruCache_get_JOURNAL_FILE_BACKUP();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *Okhttp3InternalCacheDiskLruCache_JOURNAL_FILE_BACKUP;
J2OBJC_STATIC_FIELD_OBJ_FINAL(Okhttp3InternalCacheDiskLruCache, JOURNAL_FILE_BACKUP, NSString *)

inline NSString *Okhttp3InternalCacheDiskLruCache_get_MAGIC();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *Okhttp3InternalCacheDiskLruCache_MAGIC;
J2OBJC_STATIC_FIELD_OBJ_FINAL(Okhttp3InternalCacheDiskLruCache, MAGIC, NSString *)

inline NSString *Okhttp3InternalCacheDiskLruCache_get_VERSION_1();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *Okhttp3InternalCacheDiskLruCache_VERSION_1;
J2OBJC_STATIC_FIELD_OBJ_FINAL(Okhttp3InternalCacheDiskLruCache, VERSION_1, NSString *)

inline jlong Okhttp3InternalCacheDiskLruCache_get_ANY_SEQUENCE_NUMBER();
#define Okhttp3InternalCacheDiskLruCache_ANY_SEQUENCE_NUMBER -1LL
J2OBJC_STATIC_FIELD_CONSTANT(Okhttp3InternalCacheDiskLruCache, ANY_SEQUENCE_NUMBER, jlong)

inline JavaUtilRegexPattern *Okhttp3InternalCacheDiskLruCache_get_LEGAL_KEY_PATTERN();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT JavaUtilRegexPattern *Okhttp3InternalCacheDiskLruCache_LEGAL_KEY_PATTERN;
J2OBJC_STATIC_FIELD_OBJ_FINAL(Okhttp3InternalCacheDiskLruCache, LEGAL_KEY_PATTERN, JavaUtilRegexPattern *)

FOUNDATION_EXPORT void Okhttp3InternalCacheDiskLruCache_initWithOkhttp3InternalIoFileSystem_withJavaIoFile_withInt_withInt_withLong_withJavaUtilConcurrentExecutor_(Okhttp3InternalCacheDiskLruCache *self, id<Okhttp3InternalIoFileSystem> fileSystem, JavaIoFile *directory, jint appVersion, jint valueCount, jlong maxSize, id<JavaUtilConcurrentExecutor> executor);

FOUNDATION_EXPORT Okhttp3InternalCacheDiskLruCache *new_Okhttp3InternalCacheDiskLruCache_initWithOkhttp3InternalIoFileSystem_withJavaIoFile_withInt_withInt_withLong_withJavaUtilConcurrentExecutor_(id<Okhttp3InternalIoFileSystem> fileSystem, JavaIoFile *directory, jint appVersion, jint valueCount, jlong maxSize, id<JavaUtilConcurrentExecutor> executor) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT Okhttp3InternalCacheDiskLruCache *create_Okhttp3InternalCacheDiskLruCache_initWithOkhttp3InternalIoFileSystem_withJavaIoFile_withInt_withInt_withLong_withJavaUtilConcurrentExecutor_(id<Okhttp3InternalIoFileSystem> fileSystem, JavaIoFile *directory, jint appVersion, jint valueCount, jlong maxSize, id<JavaUtilConcurrentExecutor> executor);

FOUNDATION_EXPORT Okhttp3InternalCacheDiskLruCache *Okhttp3InternalCacheDiskLruCache_createWithOkhttp3InternalIoFileSystem_withJavaIoFile_withInt_withInt_withLong_(id<Okhttp3InternalIoFileSystem> fileSystem, JavaIoFile *directory, jint appVersion, jint valueCount, jlong maxSize);

J2OBJC_TYPE_LITERAL_HEADER(Okhttp3InternalCacheDiskLruCache)

#endif

#if !defined (Okhttp3InternalCacheDiskLruCache_Snapshot_) && (INCLUDE_ALL_Okhttp3InternalCacheDiskLruCache || defined(INCLUDE_Okhttp3InternalCacheDiskLruCache_Snapshot))
#define Okhttp3InternalCacheDiskLruCache_Snapshot_

#define RESTRICT_JavaIoCloseable 1
#define INCLUDE_JavaIoCloseable 1
#include "java/io/Closeable.h"

@class IOSLongArray;
@class IOSObjectArray;
@class Okhttp3InternalCacheDiskLruCache;
@class Okhttp3InternalCacheDiskLruCache_Editor;
@protocol OkioSource;

@interface Okhttp3InternalCacheDiskLruCache_Snapshot : NSObject < JavaIoCloseable >

#pragma mark Public

- (void)close;

- (Okhttp3InternalCacheDiskLruCache_Editor *)edit;

- (jlong)getLengthWithInt:(jint)index;

- (id<OkioSource>)getSourceWithInt:(jint)index;

- (NSString *)key;

#pragma mark Package-Private

- (instancetype)initWithOkhttp3InternalCacheDiskLruCache:(Okhttp3InternalCacheDiskLruCache *)outer$
                                            withNSString:(NSString *)key
                                                withLong:(jlong)sequenceNumber
                                     withOkioSourceArray:(IOSObjectArray *)sources
                                           withLongArray:(IOSLongArray *)lengths;

@end

J2OBJC_EMPTY_STATIC_INIT(Okhttp3InternalCacheDiskLruCache_Snapshot)

FOUNDATION_EXPORT void Okhttp3InternalCacheDiskLruCache_Snapshot_initWithOkhttp3InternalCacheDiskLruCache_withNSString_withLong_withOkioSourceArray_withLongArray_(Okhttp3InternalCacheDiskLruCache_Snapshot *self, Okhttp3InternalCacheDiskLruCache *outer$, NSString *key, jlong sequenceNumber, IOSObjectArray *sources, IOSLongArray *lengths);

FOUNDATION_EXPORT Okhttp3InternalCacheDiskLruCache_Snapshot *new_Okhttp3InternalCacheDiskLruCache_Snapshot_initWithOkhttp3InternalCacheDiskLruCache_withNSString_withLong_withOkioSourceArray_withLongArray_(Okhttp3InternalCacheDiskLruCache *outer$, NSString *key, jlong sequenceNumber, IOSObjectArray *sources, IOSLongArray *lengths) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT Okhttp3InternalCacheDiskLruCache_Snapshot *create_Okhttp3InternalCacheDiskLruCache_Snapshot_initWithOkhttp3InternalCacheDiskLruCache_withNSString_withLong_withOkioSourceArray_withLongArray_(Okhttp3InternalCacheDiskLruCache *outer$, NSString *key, jlong sequenceNumber, IOSObjectArray *sources, IOSLongArray *lengths);

J2OBJC_TYPE_LITERAL_HEADER(Okhttp3InternalCacheDiskLruCache_Snapshot)

#endif

#if !defined (Okhttp3InternalCacheDiskLruCache_Editor_) && (INCLUDE_ALL_Okhttp3InternalCacheDiskLruCache || defined(INCLUDE_Okhttp3InternalCacheDiskLruCache_Editor))
#define Okhttp3InternalCacheDiskLruCache_Editor_

@class IOSBooleanArray;
@class Okhttp3InternalCacheDiskLruCache;
@class Okhttp3InternalCacheDiskLruCache_Entry;
@protocol OkioSink;
@protocol OkioSource;

@interface Okhttp3InternalCacheDiskLruCache_Editor : NSObject {
 @public
  Okhttp3InternalCacheDiskLruCache_Entry *entry__;
  IOSBooleanArray *written_;
}

#pragma mark Public

- (void)abort;

- (void)abortUnlessCommitted;

- (void)commit;

- (id<OkioSink>)newSinkWithInt:(jint)index OBJC_METHOD_FAMILY_NONE;

- (id<OkioSource>)newSourceWithInt:(jint)index OBJC_METHOD_FAMILY_NONE;

#pragma mark Package-Private

- (instancetype)initWithOkhttp3InternalCacheDiskLruCache:(Okhttp3InternalCacheDiskLruCache *)outer$
              withOkhttp3InternalCacheDiskLruCache_Entry:(Okhttp3InternalCacheDiskLruCache_Entry *)entry_;

- (void)detach;

@end

J2OBJC_EMPTY_STATIC_INIT(Okhttp3InternalCacheDiskLruCache_Editor)

J2OBJC_FIELD_SETTER(Okhttp3InternalCacheDiskLruCache_Editor, entry__, Okhttp3InternalCacheDiskLruCache_Entry *)
J2OBJC_FIELD_SETTER(Okhttp3InternalCacheDiskLruCache_Editor, written_, IOSBooleanArray *)

FOUNDATION_EXPORT void Okhttp3InternalCacheDiskLruCache_Editor_initWithOkhttp3InternalCacheDiskLruCache_withOkhttp3InternalCacheDiskLruCache_Entry_(Okhttp3InternalCacheDiskLruCache_Editor *self, Okhttp3InternalCacheDiskLruCache *outer$, Okhttp3InternalCacheDiskLruCache_Entry *entry_);

FOUNDATION_EXPORT Okhttp3InternalCacheDiskLruCache_Editor *new_Okhttp3InternalCacheDiskLruCache_Editor_initWithOkhttp3InternalCacheDiskLruCache_withOkhttp3InternalCacheDiskLruCache_Entry_(Okhttp3InternalCacheDiskLruCache *outer$, Okhttp3InternalCacheDiskLruCache_Entry *entry_) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT Okhttp3InternalCacheDiskLruCache_Editor *create_Okhttp3InternalCacheDiskLruCache_Editor_initWithOkhttp3InternalCacheDiskLruCache_withOkhttp3InternalCacheDiskLruCache_Entry_(Okhttp3InternalCacheDiskLruCache *outer$, Okhttp3InternalCacheDiskLruCache_Entry *entry_);

J2OBJC_TYPE_LITERAL_HEADER(Okhttp3InternalCacheDiskLruCache_Editor)

#endif

#if !defined (Okhttp3InternalCacheDiskLruCache_Entry_) && (INCLUDE_ALL_Okhttp3InternalCacheDiskLruCache || defined(INCLUDE_Okhttp3InternalCacheDiskLruCache_Entry))
#define Okhttp3InternalCacheDiskLruCache_Entry_

@class IOSLongArray;
@class IOSObjectArray;
@class Okhttp3InternalCacheDiskLruCache;
@class Okhttp3InternalCacheDiskLruCache_Editor;
@class Okhttp3InternalCacheDiskLruCache_Snapshot;
@protocol OkioBufferedSink;

@interface Okhttp3InternalCacheDiskLruCache_Entry : NSObject {
 @public
  NSString *key_;
  IOSLongArray *lengths_;
  IOSObjectArray *cleanFiles_;
  IOSObjectArray *dirtyFiles_;
  jboolean readable_;
  Okhttp3InternalCacheDiskLruCache_Editor *currentEditor_;
  jlong sequenceNumber_;
}

#pragma mark Package-Private

- (instancetype)initWithOkhttp3InternalCacheDiskLruCache:(Okhttp3InternalCacheDiskLruCache *)outer$
                                            withNSString:(NSString *)key;

- (void)setLengthsWithNSStringArray:(IOSObjectArray *)strings;

- (Okhttp3InternalCacheDiskLruCache_Snapshot *)snapshot;

- (void)writeLengthsWithOkioBufferedSink:(id<OkioBufferedSink>)writer;

@end

J2OBJC_EMPTY_STATIC_INIT(Okhttp3InternalCacheDiskLruCache_Entry)

J2OBJC_FIELD_SETTER(Okhttp3InternalCacheDiskLruCache_Entry, key_, NSString *)
J2OBJC_FIELD_SETTER(Okhttp3InternalCacheDiskLruCache_Entry, lengths_, IOSLongArray *)
J2OBJC_FIELD_SETTER(Okhttp3InternalCacheDiskLruCache_Entry, cleanFiles_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(Okhttp3InternalCacheDiskLruCache_Entry, dirtyFiles_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(Okhttp3InternalCacheDiskLruCache_Entry, currentEditor_, Okhttp3InternalCacheDiskLruCache_Editor *)

FOUNDATION_EXPORT void Okhttp3InternalCacheDiskLruCache_Entry_initWithOkhttp3InternalCacheDiskLruCache_withNSString_(Okhttp3InternalCacheDiskLruCache_Entry *self, Okhttp3InternalCacheDiskLruCache *outer$, NSString *key);

FOUNDATION_EXPORT Okhttp3InternalCacheDiskLruCache_Entry *new_Okhttp3InternalCacheDiskLruCache_Entry_initWithOkhttp3InternalCacheDiskLruCache_withNSString_(Okhttp3InternalCacheDiskLruCache *outer$, NSString *key) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT Okhttp3InternalCacheDiskLruCache_Entry *create_Okhttp3InternalCacheDiskLruCache_Entry_initWithOkhttp3InternalCacheDiskLruCache_withNSString_(Okhttp3InternalCacheDiskLruCache *outer$, NSString *key);

J2OBJC_TYPE_LITERAL_HEADER(Okhttp3InternalCacheDiskLruCache_Entry)

#endif

#pragma pop_macro("INCLUDE_ALL_Okhttp3InternalCacheDiskLruCache")
